name: flutter_cswiper
description: flutter_cswiper
version: 1.0.0
author: Jeffery <jefferyeral@163.com>
homepage: https://github.com/ZJFERAL/flutter_cswiper

dependencies:
  flutter:
    sdk: flutter

  transformer_page_view: ^0.1.6
  flutter_page_indicator: ^0.0.3

environment:
  sdk: ">=2.0.0-dev.48.0 <3.0.0"
  flutter: ">=0.1.4 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
